
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #      defaultZone: http://localhost:8000/eureka
      defaultZone: ${REGISTRY_URI}

server:
  port: ${APP_SERVER_PORT}

spring:
  application:
    name: "contracts-service"
  data:
    mongodb:
      uri: mongodb://${MONGO_NODE_USERNAME}:${MONGO_NODE_PASS}@${MONGO_NODE_URI}:${MONGO_NODE_PORT}/
      authentication-database: admin
      database: contracts
  security:
    secret: ${SECRET_KEY}
  rabbitmq:
   addresses: amqp://${RABBIT_NODE_USERNAME}:${RABBIT_NODE_PASS}@${RABBIT_NODE_URI}:${RABBIT_NODE_PORT}/

management:
  endpoints:
    web:
      exposure:
        include: "*"
