eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${REGISTRY_URI}

server:
  port: ${GATEWAY2_PORT}

spring:
  application:
    name: "gateway2-service"
  cloud:
    gateway:
      filter:
        remove-non-proxy-headers:
          headers:
          - dummy
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: auctionsocket
        uri: lb:ws://AUCTIONS-SERVICE/
        predicates:
        - Path=/api/auctions/ws
        filters:
        - RewritePath=/api/auctions(?<segment>/?.*), $\{segment}

      - id: auctionsocketfallback
        uri: lb://AUCTIONS-SERVICE/
        predicates:
        - Path=/api/auctions/ws
        filters:
        - RewritePath=/api/auctions(?<segment>/?.*), $\{segment}

      - id: rest
        uri: lb://GATEWAY-SERVICE
        predicates:
        - Path=/**

  data:
    mongodb:
      uri: mongodb://${MONGO_NODE_USERNAME}:${MONGO_NODE_PASS}@${MONGO_NODE_URI}:${MONGO_NODE_PORT}/
      authentication-database: admin
      database: users
  security:
    secret: ${SECRET_KEY}

# zuul:
#   routes:
#     user-service: 
#       path: /api/users/**
#       sensitiveHeaders: 
#     proposals-service:
#       path: /api/proposals/**
#       sensitiveHeaders: 
#     scheduler-service:
#       path: /api/schedules/**
#       sensitiveHeaders: 
#     contracts-service:
#       path: /api/contracts/**
#       sensitiveHeaders: 
#     auctions-service:
#       path: /api/auctions/**
#       sensitiveHeaders: 
#     webapp-service: /**
#   host:
#     socket-timeout-millis: 10000

management:
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 42000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
