eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${REGISTRY_URI}

server:
  port: ${GATEWAY_PORT}

spring:
  application:
    name: "gateway-service"

zuul:
  routes:
    user-service: /api/users/**
    proposals-service: /api/proposals/**
    scheduler-service: /api/schedules/**
    contracts-service: /api/contracts/**
    autions-ws:
      path: /api/auctions/ws/**
      url: ws://auctions-service:4000/ws
    auctions-service: /api/auctions/**
    webapp-service: /**
  host:
    socket-timeout-millis: 20000

management:
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
