eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #      defaultZone: http://localhost:8000/eureka
      defaultZone: ${REGISTRY_URI}

server:
  port: ${APP_SERVER_PORT}

spring:
  application:
    name: "scheduler-service"
  data:
    mongodb:
      uri: mongodb://${MONGO_NODE_USERNAME}:${MONGO_NODE_PASS}@${MONGO_NODE_URI}:${MONGO_NODE_PORT}/
      authentication-database: admin
      database: scheduler
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            isClustered: true
            dataSource: mongodb
          scheduler:
            instanceId: AUTO


management:
  endpoints:
    web:
      exposure:
        include: "*"
